### ISSUE TITLE
TextField check Inkonsistenz

### ISSUE THREAD

**Issue by xtj-9182** [Sycend/Apfelkuchen#12]
Wenn ich bei zb textfeldmin & eingebe dann bekomme ich eine Fehlermeldung angezeigt, so wie es sein soll, wenn ich aber 7& eingebe dann bekomme ich erst eine Fehlermeldung angezeigt wenn ich auf den Next button drücke. Es wäre vllt gut das zu vereinheitlichen, sprich also entweder sollte ich direkt bei der Eingabe immer eine Fehlermeldung bekommen oder erst wenn ich auf den Next button drücke, eventuell könnte man den Code der zzt in dem next button actionlistener ist in die Documentlistener der textfelder rein tun.

**Comment by jklinin** [comment]
ok. ich habe das erledigt. auskommentierter code brauche ich noch viellicht. 
Mit 'e ' mache ich am wochenende
