### ISSUE TITLE
textFieldUnit check muss / erlauben

### ISSUE THREAD

**Issue by xtj-9182** [Sycend/Apfelkuchen#13]
wenn ich mol/s eingebe bei Unit und jetzt auf den Next button gehe, dann
bekomme ich einen Fehler angezeigt. Das sollte aber möglich sein weil 
mol/s eine Einheit ist.

**Comment by jklinin** [comment]
ist es mol pro sekunde? (mol/s)
dann erlaube für field einheit / zeichen

**Comment by xtj-9182** [comment]
Ja mol pro sekunde (mol/s) ist gemeint.

Ich glaube das kommt aber nur wenn man auf den Next button drückt, wolltest du da nicht sowieso denn Code für die Check textfields rausnehmen (und in die Documentlistener rein hauen) ?

**Comment by jklinin** [comment]
Wen ich alles in documentlistener einpake

Gesendet von meinem BlackBerry 10-Smartphone.
Von: xtj-9182
Gesendet: Donnerstag, 22. Januar 2015 18:42
An: Sycend/Apfelkuchen
Antwort an: Sycend/Apfelkuchen
Cc: jklinin
Betreff: Re: [Apfelkuchen] textFieldUnit check muss / erlauben (#13)


Ja mol pro sekunde (mol/s) ist gemeint.

Ich glaube das kommt aber nur wenn man auf den Next button drückt, wolltest du da nicht sowieso denn Code für die Check textfields rausnehmen (und in die Documentlistener rein hauen) ?

---

**Comment by jklinin** [comment]
Wenn ich alles in docList mache, dann muss ich eine boolean variable anwenden. Diese variable wird fester blockieren, wenn die eingaben falsch sind.

Aber wenn wir z. B 5 Fehler haben, und nur eine fehler korrigieren, dann wird diese variable true, obwohl wir noch 4 fehler haben. Hast du einen anderen Vorschlag  ?

Gesendet von meinem BlackBerry 10-Smartphone.
Von: xtj-9182
Gesendet: Donnerstag, 22. Januar 2015 18:42
An: Sycend/Apfelkuchen
Antwort an: Sycend/Apfelkuchen
Cc: jklinin
Betreff: Re: [Apfelkuchen] textFieldUnit check muss / erlauben (#13)


Ja mol pro sekunde (mol/s) ist gemeint.

Ich glaube das kommt aber nur wenn man auf den Next button drückt, wolltest du da nicht sowieso denn Code für die Check textfields rausnehmen (und in die Documentlistener rein hauen) ?

---

**Comment by xtj-9182** [comment]
sollte es nicht eigentlich so sein das einfach eine JoptionPane Fehler meldung angezeigt wird ?

sprich sobald ich ein fehlerhaftes Zeichen eingebe kommt die Fehlermeldung, und dann sieht der User das und berichtigt den Fehler, Sprich es sollte doch gar nicht dazu kommen das ein User mehr als ein Falsches Zeichen eingibbt da die eingabe ja pro zeichen prüft oder?

**Comment by jklinin** [comment]
vielleicht. aber ich habe so verstanden, dass feld mit rot markiert sein sollt. 
Ich habe JOptionPane Error für die felder abschalet, weil diese Meldung sehr nervt. Ich lasse zwei überprüfungen und am Montag frage ich. Man kann immer eine Überprüfung löschen 

Date: Thu, 22 Jan 2015 23:38:47 -0800

**Comment by xtj-9182** [comment]
Ok so kannst du es ja machen, was für Überprüfungen finden denn jetzt noch statt ?

**Comment by jklinin** [comment]
Sonder Zeichen nicht erlaubt, ausser Unit(das habe ich noch nicht implementiert)
Buchstaben sind für Min, Max, SI Min/Max, m, kal, ... 
Abkürzung 8 Zechen, keine sonder Zeichen
Min/Max kann nicht kleiner als 0 sein
Max muss grösser als Min sein
SI Min != Si Max

Date: Fri, 23 Jan 2015 07:57:20 -0800

**Comment by jklinin** [comment]
ich habe mol/s erlaubt und auch bla/bla, 
bla/bla^2, bla/bla/bla, bla^2
