### ISSUE TITLE
Problem with RelevantFactors.apk

### ISSUE THREAD

**Issue by CWuetschner** [Sycend/Apfelkuchen#15]
Flo  tried to load his RelevantFactors.apk file ... he gets an alert that the file is not found ... but it is located in the default location

**Comment by xtj-9182** [comment]
I can't reproduce this.

My RelevantFactors.apk file works flawlessly.

Try deleting it and creating a new one.

What I did I deleted my old .apk file and created 4 new rows of factors 
and clicked file->save to .apk 
if I want to load this .apk file I have no problem with that.

**Comment by xtj-9182** [comment]
It might be helpful to point out that the default location is the same location that contains the

spezifikation.csv
TestCase.csv
user_spezifikation.csv
labels.xml

**Comment by xtj-9182** [comment]
If the problem persist try putting this:

System.out.println(Util.getInstance().RELEVANTFACTORS_FILE.getAbsoluteFile());

into your main and give me the location.

it could be that Something misinterprets the location maybe...

**Comment by CWuetschner** [comment]
I think flo just had bad luck ... after he made a new .apk file it worked again
